namespace: my_own_namespace
name: yandex_cloud_elk
version: "1.0.0"
readme: README.md
authors:
  - Your Name (@yourGitHubHandle)
description: Collection containing my custom file creation module and role.
license: GPL-3.0-or-later
